app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noh/', include('noh.urls')),
]

blog/urls.py
from django.urls import path
from blog import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new', views.CreatePostView.as_view(), name='post_new'),

]

noh/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'noh'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

noh_site/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noh/', include('noh.urls')),
    path('blog/', include('blog.urls'))
]

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField("タイトル", max_length=200)
    content = models.TextField("本文")
    created = models.DateTimeField("作成日", default=timezone.now)

    def __str__(self):
        return self.title

noh/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now >= self.pub_date >= now - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

blog/forms.py
from django import forms

class PostForm(forms.Form):
    title = forms.CharField(max_length=30, label='タイトル')
    content = forms.CharField(label='内容', widget=forms.Textarea())

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post
from .forms import PostForm

class IndexView(View):
    def get(self, request, *args, **kwargs):
        post_data = Post.objects.order_by('id')
        return render(request, 'blog/index.html', {
            'post_data': post_data
        })

class PostDetailView(View):
    def get(self, request, *args, **kwargs):
        post_data = Post.objects.get(id=self.kwargs['pk'])
        return render(request, 'blog/post_detail.html', {
            'post_data': post_data
        })

class CreatePostView(View, LoginRequiredMixin):
    def get(self, request, *args, **kwargs):
        form = PostForm(request.POST or None)
        return render(request, 'blog/post_form.html', {
            'form': form
        })
    def post(self, request, *args, **kwargs):
        form = PostForm(request.POST or None)
        if form.is_valid():
            post_data = Post()
            post_data.author = request.user
            post_data.title = form.cleaned_data['title']
            post_data.content = form.cleaned_data['content']
            post_data.save()
            return redirect('post_detail', post_data.id)
        return render(request, 'blog/post_form.html', {
            'form': form
        })

noh/views.py
from django import template
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, response, Http404
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Question, Choice
# Create your views here.

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return render(request, 'noh/index.html', context)
# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'noh/detail.html', {'question': question})
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'noh/results.html', {'question': question})

class IndexView(generic.ListView):
    template_name = 'noh/index.html'
    context_object_name = 'latest_question_list'
    def get_queryset(self):
        """Reutrn the last five published questions(
        not including those set to be published in the future)."""
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]
class DetailView(generic.DetailView):
    model = Question
    template_name = 'noh/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'noh/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
    return response.HttpResponseRedirect(reverse('noh:results', args=(question.id,)))

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="with=device-width", initial-scale=1.0>
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.4/"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <titile>ブログ</titile>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class = "container">
            <a class="navbar-brand" href="/">ブログ</a>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">ホーム</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'post_new' %}">投稿</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">ログアウト</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="">サインアップ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">ログイン</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main>
        <div class="container">
            {% block content%}
            {% endblock %}
        </div>
    </main>

    <footer class="py-2 bg-dark">
        <p class="m-0 text-center text-white">Copyright &copy; Django Startup 2021</p>
    </footer>

    {% block exrta_js %}
    {% endblock %}

</body>
</html>

blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block content %}

<div class="row my-4">
    <div class="col-md-8">
        {% for post in post_data %}
        <div class="card mb-4">
            <div class="card-body">
                <h2 class="card-title">{{ post.title }}</h2>
                <p class="card-text">{{ post.content|truncatechars:100 }}</p>
                <div class="btn btn-warning">詳細</div>
            </div>
            <div class="cardfooter text-muted">
                {{ post.created|date }} by {{ post.author }}
            </div>
            <a href="{% url 'post_detail' post.id %}" class="stretched-link"></a>
        </div>
        {% endfor %}
    </div>

    <div class="col-me-4">
        <div class="card">
            <h5 class="card-heder">このブログについて</h5>
            <div class="card-body">
                <p>ステップ1</p>
                <p class="mb-0">
                    能楽部用のブログサイトです
                </p>
            </div>
        </div>
    </div>

</div>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}
<h2 class="my-4">{{ post_data.title }}</h2>
<hr>
<p>{{ post_data.created }} by {{post_data.author}}</p>
<hr>
<p>{{ post_data.content|linebreaksbr }}</p>
{% if user.is_authenticated %}
    <hr>
    <div class="d-flex mb-5">
        <a href="" class="btn btn-warning mr-2">編集する</a>
        <a href="" class="btn btn-danger">削除する</a>
    </div>
{% endif %}
{% endblock %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load widget_tweaks %}

{% block content %}

<div class="my-4">
    <h2>投稿</h2>
    <form method="post">
        {% csrf_token %}
        <div class="formpost">
            {% render_field form.title class="form-control" placeholder="タイトルを入力" %}
        </div>
        <div class="formpost">
            {% render_field form.content class="form-control" placeholder="本文を入力" %}
        </div>
        <button class="btn btn-warning" type="submit">投稿する</button>
    </form>
</div>

{% endblock %}

noh/templates/noh/detail.html
<form action="{% url 'noh:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

noh/templates/noh/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'noh/style.css' %}">
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'noh:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

noh/templates/noh/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'noh:detail' question.id %}">Vote again?</a>